version: "2"
services:
  shopper:
    image: shopper:0.9
    container_name: shopper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production