apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopper-app
  template:
    metadata:
      labels:
        app: shopper-app
    spec:
      containers:
      - name: shopper-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: europe-west3-docker.pkg.dev/shopper-backend-c590c/shopper-registry/shopper-image:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"